### ISSUE TITLE
Documentation:  Use $KUBECONFIG

### ISSUE THREAD

**Issue by joslinpr** [B23admin/kubectl-config-cleanup#11]
Hi!  Thanks for a handy little utility.

In your README.md you suggest the shell script ` kubectl-config_swap`.  May I suggest that the script is more general if it uses $KUBECONFIG?  Here is a replacement version:

``` bash
#!/usr/bin/env bash
set -euo pipefail

# if $KUBECONFIG is not set, use default
KUBECONFIG=${KUBECONFIG:-~/.kube/config}
printf "Using kubeconfig <%s>\n" "$KUBECONFIG" >&2

touch "${KUBECONFIG}.swap" &&
    mv "${KUBECONFIG}" "${KUBECONFIG}.swap.tmp" &&
    mv "${KUBECONFIG}.swap" "${KUBECONFIG}" &&
    mv "${KUBECONFIG}.swap.tmp" "${KUBECONFIG}.swap" &&
    printf "Success.\n" >&2

```

**Comment by dbkegley** [comment]
Thanks for your feedback! That's a good suggestion, I'll go ahead and add it to the README
