### ISSUE TITLE
arm64 Apple M chip support

### ISSUE THREAD

**Issue by ranma2913** [B23admin/kubectl-config-cleanup#5]
# The issue:
The config-cleanup plugin doesn't have an arm64 build at this point.

# Reproduce the Problem
1. install krew on a m1 macbook
```zsh
kubectl krew version
OPTION            VALUE
GitTag            v0.4.3
GitCommit         dbfefa58
IndexURI          https://github.com/kubernetes-sigs/krew-index.git
BasePath          /Users/jsticha/.krew
IndexPath         /Users/jsticha/.krew/index/default
InstallPath       /Users/jsticha/.krew/store
BinPath           /Users/jsticha/.krew/bin
DetectedPlatform  darwin/arm64
```
2. Try and install the cleanup plugin using krew.
```zsh
kubectl krew install config-cleanup
Updated the local copy of plugin index.
Installing plugin: config-cleanup
W0421 00:02:15.690282   24442 install.go:164] failed to install plugin "config-cleanup": plugin "config-cleanup" does not offer installation for this platform
failed to install some plugins: [config-cleanup]: plugin "config-cleanup" does not offer installation for this platform
```

**Comment by dbkegley** [comment]
Hi @ranma2913, thanks for filing this! I've just been granted maintainer access to the repo so I'll try to address this ASAP but I may not get to it for a week or two

**Comment by dbkegley** [comment]
amd64 builds have been added in the latest release. I have not had a chance to push the latest release up to krew yet, but the binaries can be found on the releases page in the meantime.

https://github.com/B23admin/kubectl-config-cleanup/releases/tag/v0.6.0
